baseURL = ""
languageCode = "en-us"
title = "David Stentiford"
theme = "ezhil"
paginate = 3

copyright = "CC BY-NC-SA 3.0"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = false
disqusShortname = false

summaryLength = 20

[params]
	subtitle = "Ph.D. Candidate, Program in Modern Thought and Literature |  Stanford University"
	disableDisqusTypes = ["post","posts","page"]
	featherIconsCDN = true
	favicon = "icons/favicon.ico"
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About Me"
url = "/about-me"
weight = 2

[[menu.main]]
name = "CV"
url = "/cv"
weight = 3

[[menu.main]]
name = "Teaching"
url = "/teaching"
weight = 4

[[menu.main]]
name = "Writing"
url = "/posts"
weight = 5

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 5

[taxonomies]
   tag = "tags"
